### ISSUE TITLE
ImportError: cannot import name 'DataError' from 'pandas.core.base'

### ISSUE THREAD

**Issue by JulioBarros** [ydataai/pandas-profiling#1118]
I have the same issue:

### Discussed in https://github.com/ydataai/pandas-profiling/discussions/1066

<div type='discussions-op-text'>

<sup>Originally posted by **etanaga** September 22, 2022</sup>
Hi all.
I have an issue with pandas_profiling, currently my environment  

- Conda 4.14.0 
- Python 3.9.13
- pandas 1.5.0
- pandas-profiling 2.9.0

And received an error while try to import pandas_profilling

from pandas_profiling import ProfileReport
profile = ProfileReport(retail_raw)
profile.to_notebook_iframe()

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Input In [11], in <cell line: 1>()
----> 1 from pandas_profiling import ProfileReport
      2 profile = ProfileReport(retail_raw)
      3 profile.to_notebook_iframe()

File ~\Anaconda3\lib\site-packages\pandas_profiling\__init__.py:7, in <module>
      1 """Main module of pandas-profiling.
      2 
      3 .. include:: ../../README.md
      4 """
      6 from pandas_profiling.config import Config, config
----> 7 from pandas_profiling.controller import pandas_decorator
      8 from pandas_profiling.profile_report import ProfileReport
      9 from pandas_profiling.version import __version__

File ~\Anaconda3\lib\site-packages\pandas_profiling\controller\pandas_decorator.py:4, in <module>
      1 """This file add the decorator on the DataFrame object."""
      2 from pandas import DataFrame
----> 4 from pandas_profiling.__init__ import ProfileReport
      7 def profile_report(df, **kwargs) -> ProfileReport:
      8     """Profile a DataFrame.
      9 
     10     Args:
   (...)
     15         A ProfileReport of the DataFrame.
     16     """

File ~\Anaconda3\lib\site-packages\pandas_profiling\__init__.py:8, in <module>
      6 from pandas_profiling.config import Config, config
      7 from pandas_profiling.controller import pandas_decorator
----> 8 from pandas_profiling.profile_report import ProfileReport
      9 from pandas_profiling.version import __version__
     11 clear_config = ProfileReport.clear_config

File ~\Anaconda3\lib\site-packages\pandas_profiling\profile_report.py:11, in <module>
      8 from tqdm.auto import tqdm
     10 from pandas_profiling.config import config
---> 11 from pandas_profiling.model.describe import describe as describe_df
     12 from pandas_profiling.model.messages import MessageType
     13 from pandas_profiling.report import get_report_structure

File ~\Anaconda3\lib\site-packages\pandas_profiling\model\describe.py:11, in <module>
      9 from pandas_profiling.config import config as config
     10 from pandas_profiling.model.base import Variable
---> 11 from pandas_profiling.model.correlations import calculate_correlation
     12 from pandas_profiling.model.sample import Sample, get_sample
     13 from pandas_profiling.model.summary import (
     14     get_duplicates,
     15     get_messages,
   (...)
     19     get_table_stats,
     20 )

File ~\Anaconda3\lib\site-packages\pandas_profiling\model\correlations.py:11, in <module>
      9 import pandas as pd
     10 from confuse import NotFoundError
---> 11 from pandas.core.base import DataError
     12 from scipy import stats
     14 from pandas_profiling.config import config

ImportError: cannot import name 'DataError' from 'pandas.core.base' (C:\Users\etana\Anaconda3\lib\site-packages\pandas\core\base.py)

Need the help to fix my problem.
Thanks

</div>

**Comment by JulioBarros** [comment]
Though it works with python 3.9

**Comment by fabclmnt** [comment]
@JulioBarros Can you please update pandas-profiling version to the latest: 3.4.0?

And let me know whether it works. This issue is expected to be already sorted.

**Comment by JulioBarros** [comment]
@fabclmnt  This is strange.  The env of the project where I saw this has changed quite a bit so I can't reproduce it in that env. But I had just installed pandas-profiling so believe it was the latest version.

However I just created a new env with the minimal number of packages and Python 3.10.8 and it worked fine.

If it was previously fixed perhaps I got an old/cached version instead.

Looks like it works now.  Thanks.

**Comment by fabclmnt** [comment]
Happy to know @JulioBarros !

**Comment by windowshopr** [comment]
Ran into this issue as well, has to do with it not being compatible with 3.11 is my guess.

**Comment by frbelotto** [comment]
Same issue here. As I am on python 3.11, it makes sense.

**Comment by IloBe** [comment]
Hi all, I have the same issue with Python 3.10.9 and pandas-profiling 3.6.3

**Comment by fabclmnt** [comment]
> Ran into this issue as well, has to do with it not being compatible with 3.11 is my guess.

Not compatible with 3.11 indeed. There is an issue open to support 3.11 , but indeed 3.11 is not officially supported.
